name: Build Fabric Mod

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Build with Gradle
        run: gradle build --no-daemon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blockwalker-jar
          path: build/libs/*.jar
